[package]
name = "rust-lib"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
